sudo: require
language: cpp
dist: trusty

compiler:
  - gcc

before_script:
  - sudo apt-get update -q
  - sudo apt-get install cmake
  - sudo apt-get install libopencv-dev
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./ray test.ppm 1000 1000
  
